package com.taobao.idea.wuluwa;

import com.intellij.openapi.fileChooser.FileChooser;
import com.intellij.openapi.fileChooser.FileChooserDescriptor;
import com.intellij.openapi.ui.Messages;
import com.intellij.openapi.vfs.VirtualFile;
import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.jgoodies.forms.layout.CellConstraints;
import com.jgoodies.forms.layout.FormLayout;

import javax.swing.*;
import javax.swing.border.TitledBorder;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;

/**
 * Author: yunshu.xw
 */
public class WuluForm {
    private JPanel rootFrame;
    private JTextField wordSrc;
    private JLabel labelSrc;
    private JTextField wordDest;
    private JLabel labelDest;
    private JButton testButton;
    private String testSrcPath;

    public WuluForm() {
        $$$setupUI$$$();
        testButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                FileChooserDescriptor fcd = new FileChooserDescriptor(true, true, false, false, false, false);
                fcd.setDescription("文件目录");
                fcd.setShowFileSystemRoots(true);
                fcd.setTitle("请选择测试文件...");
                VirtualFile vf = FileChooser.chooseFile(rootFrame, fcd);
                if (null == vf) {
                    return;
                }
                testSrcPath = vf.getPresentableUrl();
                FileAnalysts fileAnalysts = new FileAnalysts();
                String result = fileAnalysts.getDestFilePath(testSrcPath, wordSrc.getText(), wordDest.getText());
                StringBuffer showMessage = new StringBuffer();
                showMessage.append("源地址:").append(testSrcPath).append("\n").append("转换结果：").append(result);
                Messages.showMessageDialog(showMessage.toString(), "Test结果", Messages.getInformationIcon());
            }
        });
    }

    private void createUIComponents() {
        rootFrame = new JPanel();
    }

    public void setData(Wuluboy data) {
        wordSrc.setText(data.getSrcPath());
        wordDest.setText(data.getDestPath());
    }

    public void getData(Wuluboy data) {
        data.setSrcPath(wordSrc.getText());
        data.setDestPath(wordDest.getText());
    }

    public boolean isModified(Wuluboy data) {
        if (wordSrc.getText() != null ? !wordSrc.getText().equals(data.getSrcPath()) : data.getSrcPath() != null)
            return true;
        if (wordDest.getText() != null ? !wordDest.getText().equals(data.getDestPath()) : data.getDestPath() != null)
            return true;
        return false;
    }

    private void eventBindIDEA(JButton button, final JTextField word) {
        button.addMouseListener(new MouseAdapter() {
            public void mouseClicked(MouseEvent e) {
                FileChooserDescriptor fcd = new FileChooserDescriptor(false, true, false, false, false, false);
                fcd.setDescription("文件目录");
                fcd.setTitle("请选择要上传的文件...");
                VirtualFile vf = FileChooser.chooseFile(rootFrame, fcd);
                word.setText(vf.getPath());
            }
        });
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        createUIComponents();
        rootFrame.setLayout(new FormLayout("right:-146px:grow,left:4dlu:noGrow,fill:p:grow", "center:max(d;4px):noGrow,top:4dlu:noGrow,center:max(d;4px):noGrow,top:4dlu:noGrow,center:max(d;4px):noGrow"));
        rootFrame.setAlignmentX(0.6f);
        rootFrame.setAlignmentY(0.4f);
        rootFrame.setBorder(BorderFactory.createTitledBorder(BorderFactory.createLineBorder(new Color(-16777216)), null, TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, null, new Color(-16777216)));
        labelDest = new JLabel();
        labelDest.setAlignmentY(0.4f);
        labelDest.setText("请填写目标路径的替换地址：");
        CellConstraints cc = new CellConstraints();
        rootFrame.add(labelDest, cc.xy(1, 3, CellConstraints.RIGHT, CellConstraints.DEFAULT));
        testButton = new JButton();
        testButton.setText("Test路径");
        rootFrame.add(testButton, cc.xy(3, 5, CellConstraints.LEFT, CellConstraints.DEFAULT));
        wordSrc = new JTextField();
        wordSrc.setPreferredSize(new Dimension(10, 23));
        rootFrame.add(wordSrc, cc.xy(3, 1));
        wordDest = new JTextField();
        wordDest.setAlignmentX(0.4f);
        wordDest.setPreferredSize(new Dimension(10, 23));
        rootFrame.add(wordDest, cc.xy(3, 3));
        labelSrc = new JLabel();
        labelSrc.setAlignmentY(0.4f);
        labelSrc.setAutoscrolls(false);
        labelSrc.setText("请填写修改文件所在目录要替换的地址：");
        rootFrame.add(labelSrc, cc.xy(1, 1, CellConstraints.RIGHT, CellConstraints.DEFAULT));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return rootFrame;
    }
}